// <auto-generated />
using System;
using GMAO.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GMAO.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260714180439_AjoutTelephoneUtilisateur")]
    partial class AjoutTelephoneUtilisateur
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("CompetenceIngenieur", b =>
                {
                    b.Property<int>("CompetencesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IngenieursId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CompetencesId", "IngenieursId");

                    b.HasIndex("IngenieursId");

                    b.ToTable("CompetenceIngenieur");
                });

            modelBuilder.Entity("GMAO.Domain.Entities.Interventions.CheckListCloture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Alarmes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Alimentation")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutotestOk")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Batterie")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CalibrationDebit")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CalibrationO2")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Commentaire")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreePar")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InterventionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModifiePar")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TestEtancheite")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ValidationFinale")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InterventionId")
                        .IsUnique();

                    b.ToTable("CheckListsCloture");
                });

            modelBuilder.Entity("GMAO.Domain.Entities.Interventions.HistoriqueEtatIntervention", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AncienEtat")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Auteur")
                        .HasColumnType("TEXT");

                    b.Property<string>("Commentaire")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreePar")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateChangement")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InterventionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModifiePar")
                        .HasColumnType("TEXT");

                    b.Property<int>("NouvelEtat")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InterventionId");

                    b.ToTable("HistoriquesEtatIntervention");
                });

            modelBuilder.Entity("GMAO.Domain.Entities.Interventions.Intervention", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cause")
                        .HasColumnType("TEXT");

                    b.Property<string>("Commentaires")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreePar")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateCloture")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Diagnostic")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Etat")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HopitalId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IngenieurId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MainOeuvre")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiePar")
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroDI")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PanneId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PatientConnecte")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Priorite")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RespirateurId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Signature")
                        .HasColumnType("TEXT");

                    b.Property<int>("TempsDeplacement")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TempsReparation")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Urgence")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HopitalId");

                    b.HasIndex("IngenieurId");

                    b.HasIndex("NumeroDI")
                        .IsUnique();

                    b.HasIndex("PanneId");

                    b.HasIndex("RespirateurId");

                    b.ToTable("Interventions");
                });

            modelBuilder.Entity("GMAO.Domain.Entities.Interventions.LignePieceIntervention", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreePar")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InterventionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModifiePar")
                        .HasColumnType("TEXT");

                    b.Property<int>("PieceId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PrixUnitaire")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantite")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InterventionId");

                    b.HasIndex("PieceId");

                    b.ToTable("LignesPieceIntervention");
                });

            modelBuilder.Entity("GMAO.Domain.Entities.Interventions.Panne", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreePar")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiePar")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pannes");
                });

            modelBuilder.Entity("GMAO.Domain.Entities.Interventions.PhotoDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CheminFichier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreePar")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InterventionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Legende")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiePar")
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeContenu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InterventionId");

                    b.ToTable("PiecesJointes");
                });

            modelBuilder.Entity("GMAO.Domain.Entities.Interventions.Rapport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CheminPdf")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreePar")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateGeneration")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InterventionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModifiePar")
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroRapport")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InterventionId")
                        .IsUnique();

                    b.ToTable("Rapports");
                });

            modelBuilder.Entity("GMAO.Domain.Entities.Interventions.Symptome", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreePar")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiePar")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Symptomes");
                });

            modelBuilder.Entity("GMAO.Domain.Entities.Notifications.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreePar")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DestinataireId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DestinataireUtilisateurId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Lu")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiePar")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReferenceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReferenceType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DestinataireId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("GMAO.Domain.Entities.Parc.BlocOperatoire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreePar")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModifiePar")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ServiceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.ToTable("BlocsOperatoires");
                });

            modelBuilder.Entity("GMAO.Domain.Entities.Parc.DocumentTechnique", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CheminFichier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreePar")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ModeleRespirateurId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModifiePar")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RespirateurId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ModeleRespirateurId");

                    b.HasIndex("RespirateurId");

                    b.ToTable("DocumentsTechniques");
                });

            modelBuilder.Entity("GMAO.Domain.Entities.Parc.Hopital", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adresse")
                        .HasColumnType("TEXT");

                    b.Property<string>("Contact")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreePar")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModifiePar")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telephone")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Hopitaux");
                });

            modelBuilder.Entity("GMAO.Domain.Entities.Parc.ModeleRespirateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Constructeur")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreePar")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Gamme")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiePar")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ModelesRespirateur");
                });

            modelBuilder.Entity("GMAO.Domain.Entities.Parc.Respirateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuteurHorsService")
                        .HasColumnType("TEXT");

                    b.Property<int?>("BlocOperatoireId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodeInterne")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CodeQr")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreePar")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateFinGarantie")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateHorsService")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateMiseEnService")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Etat")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModeleRespirateurId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModifiePar")
                        .HasColumnType("TEXT");

                    b.Property<string>("MotifHorsService")
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroContrat")
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroSerie")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<bool>("SousContrat")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VersionLogicielle")
                        .HasColumnType("TEXT");

                    b.Property<string>("VersionMaterielle")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BlocOperatoireId");

                    b.HasIndex("CodeQr")
                        .IsUnique();

                    b.HasIndex("ModeleRespirateurId");

                    b.HasIndex("NumeroSerie")
                        .IsUnique();

                    b.ToTable("Respirateurs");
                });

            modelBuilder.Entity("GMAO.Domain.Entities.Parc.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreePar")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HopitalId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModifiePar")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HopitalId");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("GMAO.Domain.Entities.Pieces.CategoriePiece", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreePar")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModifiePar")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CategoriesPiece");
                });

            modelBuilder.Entity("GMAO.Domain.Entities.Pieces.Fournisseur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Contact")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreePar")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModifiePar")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telephone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Fournisseurs");
                });

            modelBuilder.Entity("GMAO.Domain.Entities.Pieces.MouvementStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Auteur")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreePar")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateMouvement")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModifiePar")
                        .HasColumnType("TEXT");

                    b.Property<string>("Motif")
                        .HasColumnType("TEXT");

                    b.Property<int>("PieceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantite")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PieceId");

                    b.ToTable("MouvementsStock");
                });

            modelBuilder.Entity("GMAO.Domain.Entities.Pieces.PanneePiece", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreePar")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModifiePar")
                        .HasColumnType("TEXT");

                    b.Property<int>("PanneId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PieceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Probabilite")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PanneId");

                    b.HasIndex("PieceId");

                    b.ToTable("PannesPieces");
                });

            modelBuilder.Entity("GMAO.Domain.Entities.Pieces.Piece", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoriePieceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Compatible")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreePar")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DatePeremption")
                        .HasColumnType("TEXT");

                    b.Property<string>("Emplacement")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FournisseurId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModifiePar")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Prix")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StockMinimum")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoriePieceId");

                    b.HasIndex("FournisseurId");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.ToTable("Pieces");
                });

            modelBuilder.Entity("GMAO.Domain.Entities.Planning.Competence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreePar")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ModeleRespirateurId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModifiePar")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ModeleRespirateurId");

                    b.ToTable("Competences");
                });

            modelBuilder.Entity("GMAO.Domain.Entities.Planning.Conge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreePar")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IngenieurId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModifiePar")
                        .HasColumnType("TEXT");

                    b.Property<string>("Motif")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IngenieurId");

                    b.ToTable("Conges");
                });

            modelBuilder.Entity("GMAO.Domain.Entities.Planning.Ingenieur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreePar")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Disponible")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModifiePar")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telephone")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UtilisateurId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Zone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("Ingenieurs");
                });

            modelBuilder.Entity("GMAO.Domain.Entities.Securite.HistoriqueConnexion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdresseIp")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreePar")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateConnexion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("TEXT");

                    b.Property<string>("Detail")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModifiePar")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Succes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("HistoriqueConnexions");
                });

            modelBuilder.Entity("GMAO.Domain.Entities.Securite.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Actif")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreePar")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DerniereConnexion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiePar")
                        .HasColumnType("TEXT");

                    b.Property<string>("MotDePasseHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Telephone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("InterventionSymptome", b =>
                {
                    b.Property<int>("InterventionsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SymptomesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("InterventionsId", "SymptomesId");

                    b.HasIndex("SymptomesId");

                    b.ToTable("InterventionSymptome");
                });

            modelBuilder.Entity("CompetenceIngenieur", b =>
                {
                    b.HasOne("GMAO.Domain.Entities.Planning.Competence", null)
                        .WithMany()
                        .HasForeignKey("CompetencesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GMAO.Domain.Entities.Planning.Ingenieur", null)
                        .WithMany()
                        .HasForeignKey("IngenieursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GMAO.Domain.Entities.Interventions.CheckListCloture", b =>
                {
                    b.HasOne("GMAO.Domain.Entities.Interventions.Intervention", "Intervention")
                        .WithOne("CheckList")
                        .HasForeignKey("GMAO.Domain.Entities.Interventions.CheckListCloture", "InterventionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Intervention");
                });

            modelBuilder.Entity("GMAO.Domain.Entities.Interventions.HistoriqueEtatIntervention", b =>
                {
                    b.HasOne("GMAO.Domain.Entities.Interventions.Intervention", "Intervention")
                        .WithMany("HistoriqueEtats")
                        .HasForeignKey("InterventionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Intervention");
                });

            modelBuilder.Entity("GMAO.Domain.Entities.Interventions.Intervention", b =>
                {
                    b.HasOne("GMAO.Domain.Entities.Parc.Hopital", "Hopital")
                        .WithMany()
                        .HasForeignKey("HopitalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GMAO.Domain.Entities.Planning.Ingenieur", "Ingenieur")
                        .WithMany("Interventions")
                        .HasForeignKey("IngenieurId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GMAO.Domain.Entities.Interventions.Panne", "Panne")
                        .WithMany("Interventions")
                        .HasForeignKey("PanneId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GMAO.Domain.Entities.Parc.Respirateur", "Respirateur")
                        .WithMany("Interventions")
                        .HasForeignKey("RespirateurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hopital");

                    b.Navigation("Ingenieur");

                    b.Navigation("Panne");

                    b.Navigation("Respirateur");
                });

            modelBuilder.Entity("GMAO.Domain.Entities.Interventions.LignePieceIntervention", b =>
                {
                    b.HasOne("GMAO.Domain.Entities.Interventions.Intervention", "Intervention")
                        .WithMany("PiecesUtilisees")
                        .HasForeignKey("InterventionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GMAO.Domain.Entities.Pieces.Piece", "Piece")
                        .WithMany()
                        .HasForeignKey("PieceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Intervention");

                    b.Navigation("Piece");
                });

            modelBuilder.Entity("GMAO.Domain.Entities.Interventions.PhotoDocument", b =>
                {
                    b.HasOne("GMAO.Domain.Entities.Interventions.Intervention", "Intervention")
                        .WithMany("PiecesJointes")
                        .HasForeignKey("InterventionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Intervention");
                });

            modelBuilder.Entity("GMAO.Domain.Entities.Interventions.Rapport", b =>
                {
                    b.HasOne("GMAO.Domain.Entities.Interventions.Intervention", "Intervention")
                        .WithOne("Rapport")
                        .HasForeignKey("GMAO.Domain.Entities.Interventions.Rapport", "InterventionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Intervention");
                });

            modelBuilder.Entity("GMAO.Domain.Entities.Notifications.Notification", b =>
                {
                    b.HasOne("GMAO.Domain.Entities.Securite.Utilisateur", "Destinataire")
                        .WithMany()
                        .HasForeignKey("DestinataireId");

                    b.Navigation("Destinataire");
                });

            modelBuilder.Entity("GMAO.Domain.Entities.Parc.BlocOperatoire", b =>
                {
                    b.HasOne("GMAO.Domain.Entities.Parc.Service", "Service")
                        .WithMany("BlocsOperatoires")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("GMAO.Domain.Entities.Parc.DocumentTechnique", b =>
                {
                    b.HasOne("GMAO.Domain.Entities.Parc.ModeleRespirateur", "Modele")
                        .WithMany("Documents")
                        .HasForeignKey("ModeleRespirateurId");

                    b.HasOne("GMAO.Domain.Entities.Parc.Respirateur", "Respirateur")
                        .WithMany("Documents")
                        .HasForeignKey("RespirateurId");

                    b.Navigation("Modele");

                    b.Navigation("Respirateur");
                });

            modelBuilder.Entity("GMAO.Domain.Entities.Parc.Respirateur", b =>
                {
                    b.HasOne("GMAO.Domain.Entities.Parc.BlocOperatoire", "BlocOperatoire")
                        .WithMany("Respirateurs")
                        .HasForeignKey("BlocOperatoireId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GMAO.Domain.Entities.Parc.ModeleRespirateur", "Modele")
                        .WithMany("Respirateurs")
                        .HasForeignKey("ModeleRespirateurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BlocOperatoire");

                    b.Navigation("Modele");
                });

            modelBuilder.Entity("GMAO.Domain.Entities.Parc.Service", b =>
                {
                    b.HasOne("GMAO.Domain.Entities.Parc.Hopital", "Hopital")
                        .WithMany("Services")
                        .HasForeignKey("HopitalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hopital");
                });

            modelBuilder.Entity("GMAO.Domain.Entities.Pieces.MouvementStock", b =>
                {
                    b.HasOne("GMAO.Domain.Entities.Pieces.Piece", "Piece")
                        .WithMany("Mouvements")
                        .HasForeignKey("PieceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Piece");
                });

            modelBuilder.Entity("GMAO.Domain.Entities.Pieces.PanneePiece", b =>
                {
                    b.HasOne("GMAO.Domain.Entities.Interventions.Panne", "Panne")
                        .WithMany("PiecesSuspectes")
                        .HasForeignKey("PanneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GMAO.Domain.Entities.Pieces.Piece", "Piece")
                        .WithMany("PannesAssociees")
                        .HasForeignKey("PieceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Panne");

                    b.Navigation("Piece");
                });

            modelBuilder.Entity("GMAO.Domain.Entities.Pieces.Piece", b =>
                {
                    b.HasOne("GMAO.Domain.Entities.Pieces.CategoriePiece", "Categorie")
                        .WithMany("Pieces")
                        .HasForeignKey("CategoriePieceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GMAO.Domain.Entities.Pieces.Fournisseur", "Fournisseur")
                        .WithMany("Pieces")
                        .HasForeignKey("FournisseurId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Categorie");

                    b.Navigation("Fournisseur");
                });

            modelBuilder.Entity("GMAO.Domain.Entities.Planning.Competence", b =>
                {
                    b.HasOne("GMAO.Domain.Entities.Parc.ModeleRespirateur", "Modele")
                        .WithMany()
                        .HasForeignKey("ModeleRespirateurId");

                    b.Navigation("Modele");
                });

            modelBuilder.Entity("GMAO.Domain.Entities.Planning.Conge", b =>
                {
                    b.HasOne("GMAO.Domain.Entities.Planning.Ingenieur", "Ingenieur")
                        .WithMany("Conges")
                        .HasForeignKey("IngenieurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingenieur");
                });

            modelBuilder.Entity("GMAO.Domain.Entities.Planning.Ingenieur", b =>
                {
                    b.HasOne("GMAO.Domain.Entities.Securite.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("GMAO.Domain.Entities.Securite.HistoriqueConnexion", b =>
                {
                    b.HasOne("GMAO.Domain.Entities.Securite.Utilisateur", "Utilisateur")
                        .WithMany("HistoriqueConnexions")
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("InterventionSymptome", b =>
                {
                    b.HasOne("GMAO.Domain.Entities.Interventions.Intervention", null)
                        .WithMany()
                        .HasForeignKey("InterventionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GMAO.Domain.Entities.Interventions.Symptome", null)
                        .WithMany()
                        .HasForeignKey("SymptomesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GMAO.Domain.Entities.Interventions.Intervention", b =>
                {
                    b.Navigation("CheckList");

                    b.Navigation("HistoriqueEtats");

                    b.Navigation("PiecesJointes");

                    b.Navigation("PiecesUtilisees");

                    b.Navigation("Rapport");
                });

            modelBuilder.Entity("GMAO.Domain.Entities.Interventions.Panne", b =>
                {
                    b.Navigation("Interventions");

                    b.Navigation("PiecesSuspectes");
                });

            modelBuilder.Entity("GMAO.Domain.Entities.Parc.BlocOperatoire", b =>
                {
                    b.Navigation("Respirateurs");
                });

            modelBuilder.Entity("GMAO.Domain.Entities.Parc.Hopital", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("GMAO.Domain.Entities.Parc.ModeleRespirateur", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Respirateurs");
                });

            modelBuilder.Entity("GMAO.Domain.Entities.Parc.Respirateur", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Interventions");
                });

            modelBuilder.Entity("GMAO.Domain.Entities.Parc.Service", b =>
                {
                    b.Navigation("BlocsOperatoires");
                });

            modelBuilder.Entity("GMAO.Domain.Entities.Pieces.CategoriePiece", b =>
                {
                    b.Navigation("Pieces");
                });

            modelBuilder.Entity("GMAO.Domain.Entities.Pieces.Fournisseur", b =>
                {
                    b.Navigation("Pieces");
                });

            modelBuilder.Entity("GMAO.Domain.Entities.Pieces.Piece", b =>
                {
                    b.Navigation("Mouvements");

                    b.Navigation("PannesAssociees");
                });

            modelBuilder.Entity("GMAO.Domain.Entities.Planning.Ingenieur", b =>
                {
                    b.Navigation("Conges");

                    b.Navigation("Interventions");
                });

            modelBuilder.Entity("GMAO.Domain.Entities.Securite.Utilisateur", b =>
                {
                    b.Navigation("HistoriqueConnexions");
                });
#pragma warning restore 612, 618
        }
    }
}
